// Copyright (c) 2026 Digital X Co., Ltd.
//
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"os"
	"strings"
	"testing"

	"github.com/digitalx-official/digitalx-cli/internal/envalias"
)

// The .mcpb manifest is generated by a shell script, so no Go type covers it and
// nothing else in the build would notice a bad edit — the bundle only fails at
// install time, on a user's machine. These pin the fields whose values are
// contracts rather than choices.
const mcpbScript = "scripts/build-mcpb.sh"

func mcpbSource(t *testing.T) string {
	t.Helper()
	b, err := os.ReadFile(mcpbScript)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

// TestMCPBManifestPins covers the manifest fields that a host, an installed
// bundle, or the CLI itself depends on:
//
//   - `name` is the extension's install key. An MCPB host keys the installed
//     extension on it, so a different value installs a SECOND extension next to
//     one a user already has — two servers, two copies of every tool. Both it and
//     `display_name` carry the product's name; a Desktop Extension has no
//     self-update and no migration, so a user with an older bundle removes it by
//     hand.
//   - the entry point and command must name the binary the bundle actually
//     stages, or the host launches nothing.
//   - the injected env names must be ones the CLI reads.
func TestMCPBManifestPins(t *testing.T) {
	src := mcpbSource(t)
	for _, want := range []string{
		`"name": "digitalx",`,
		`"display_name": "Digital X",`,
		`binname="dgx-cli"`,
		`entry_point="server/$binname"`,
		`command_path='${__dirname}/server/'"$binname"`,
		`"entry_point": "$entry_point",`,
		`"command": "$command_path",`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("%s no longer contains %s", mcpbScript, want)
		}
	}

	// The env names the manifest injects are read through the env shim, so they
	// must carry its canonical prefix — a name outside it is read verbatim, with
	// no legacy fallback, and an installed bundle's checkboxes would go dead.
	for _, knob := range []string{"MCP_READ_ONLY", "MCP_MULTI_KEY"} {
		canonical := envalias.Prefix + knob
		if !strings.Contains(src, `"`+canonical+`":`) {
			t.Errorf("%s must inject %s", mcpbScript, canonical)
		}
		if strings.Contains(src, `"`+envalias.LegacyPrefix+knob+`":`) {
			t.Errorf("%s still injects the legacy %s", mcpbScript, envalias.LegacyPrefix+knob)
		}
	}
}
