// Copyright (c) 2026 Digital X Co., Ltd.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by scripts/update-deno.sh; DO NOT EDIT.
// Source: https://github.com/denoland/deno/releases/tag/v2.9.1

package deno

// Version is the pinned Deno release digitalx-cli downloads as the managed
// sandbox runtime. Bump it by re-running scripts/update-deno.sh.
const Version = "v2.9.1"

// checksums maps "<GOOS>/<GOARCH>" to the SHA-256 of that platform's
// deno-<target>.zip release asset. A download whose hash does not match is
// refused. Linux is glibc-only (Deno ships no musl build).
var checksums = map[string]string{
	"darwin/arm64":  "ee3473502118eab301eca93aa6b31d6b0b6c1602d0f59e4cb89d4a262b12f6e7",
	"darwin/amd64":  "89cbc8c974247772d9200724741b4e692ef49fe470b2ff555da905817c3daa11",
	"linux/arm64":   "0a60d079fa79635a59803074dbbfe86ccc35746dc2c4f8d73f2e50338b3283a9",
	"linux/amd64":   "710c54d63477d1100844ef4818f19507ce0dbf40510903b1d883f19e394446a2",
	"windows/arm64": "57e282c6f8e92a8b79f570b37b5962bcd347ab49471e1dbc97ffbd4af3d36632",
	"windows/amd64": "ab310b4232cca207d40ffa41867e93aaf9f893802bc76756e74f486a6b21b371",
}
