#!/usr/bin/env bash
#
# Copyright (c) 2026 Digital X Co., Ltd.
#
# SPDX-License-Identifier: Apache-2.0
#
# update-deno.sh — re-pin the managed Deno runtime that korbit-cli downloads for
# the sandbox. Regenerates internal/sandbox/deno_pinned.go with the chosen Deno
# release version and the SHA-256 of each platform's release zip.
#
# Usage:
#   scripts/update-deno.sh            # pin the latest Deno release
#   scripts/update-deno.sh v2.8.3     # pin a specific release
#
# Requires: gh (authenticated GitHub CLI). Run from anywhere inside the repo.
#
# The checksums come from the GitHub release assets' own `digest` field, so the
# pin is verifiable: korbit-cli refuses a downloaded Deno whose SHA-256 does not
# match the value written here.
set -euo pipefail

# Deno release target triple -> Go "<GOOS>/<GOARCH>" (every platform korbit-cli
# may run on; Deno publishes glibc-only Linux, so musl/Alpine has no managed Deno).
TARGETS=(
	"aarch64-apple-darwin:darwin/arm64"
	"x86_64-apple-darwin:darwin/amd64"
	"aarch64-unknown-linux-gnu:linux/arm64"
	"x86_64-unknown-linux-gnu:linux/amd64"
	"aarch64-pc-windows-msvc:windows/arm64"
	"x86_64-pc-windows-msvc:windows/amd64"
)

REPO="denoland/deno"
OUT_REL="internal/sandbox/deno/pinned.go"

command -v gh >/dev/null || { echo "error: gh (GitHub CLI) is required" >&2; exit 1; }

# Resolve the module root (parent of this script's dir) so the output path is stable.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$ROOT/$OUT_REL"

VERSION="${1:-}"
if [ -z "$VERSION" ]; then
	VERSION="$(gh api "repos/$REPO/releases/latest" --jq .tag_name)"
fi
echo "Pinning Deno $VERSION (from github.com/$REPO)" >&2

# One API call: collect "name<TAB>digest" for every asset in the release.
ASSETS="$(gh api "repos/$REPO/releases/tags/$VERSION" --jq '.assets[] | "\(.name)\t\(.digest // "")"')"

digest_for() { # asset-name -> bare sha256 hex (empty if missing)
	printf '%s\n' "$ASSETS" | awk -F'\t' -v n="$1" '$1==n {sub(/^sha256:/,"",$2); print $2}'
}

tmp="$(mktemp)"
{
	echo "// Copyright (c) 2026 Digital X Co., Ltd."
	echo "//"
	echo "// SPDX-License-Identifier: Apache-2.0"
	echo
	echo "// Code generated by scripts/update-deno.sh; DO NOT EDIT."
	echo "// Source: https://github.com/$REPO/releases/tag/$VERSION"
	echo
	echo "package deno"
	echo
	echo "// Version is the pinned Deno release korbit-cli downloads as the managed"
	echo "// sandbox runtime. Bump it by re-running scripts/update-deno.sh."
	echo "const Version = \"$VERSION\""
	echo
	echo "// checksums maps \"<GOOS>/<GOARCH>\" to the SHA-256 of that platform's"
	echo "// deno-<target>.zip release asset. A download whose hash does not match is"
	echo "// refused. Linux is glibc-only (Deno ships no musl build)."
	echo "var checksums = map[string]string{"
} >"$tmp"

missing=0
for pair in "${TARGETS[@]}"; do
	target="${pair%%:*}"
	plat="${pair##*:}"
	sha="$(digest_for "deno-$target.zip")"
	if [ -z "$sha" ]; then
		echo "error: no sha256 digest for deno-$target.zip in $VERSION" >&2
		missing=1
		continue
	fi
	printf '\t"%s": "%s",\n' "$plat" "$sha" >>"$tmp"
done
echo "}" >>"$tmp"

if [ "$missing" -ne 0 ]; then
	rm -f "$tmp"
	echo "error: release $VERSION is missing one or more platform zips; not writing $OUT_REL" >&2
	exit 1
fi

mkdir -p "$(dirname "$OUT")"
if command -v gofmt >/dev/null; then
	gofmt "$tmp" >"$OUT"
	rm -f "$tmp"
else
	mv "$tmp" "$OUT"
fi

echo "wrote $OUT_REL (Deno $VERSION)" >&2
